version: '3.0'
language: pl
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: FallbackClassifier
  threshold: 0.7
- name: DucklingEntityExtractor
#  url: http://localhost:8000
  url: http://duckling.rasa.com:8000
    dimensions:
      - amount-of-money
      - time
      - number
    locale: "pl_PL"
    timezone: "Europe/Warsaw"
    timeout: 3
- name: SpacyNLP
  model: pl_core_news_lg
  case_sensitive: false
- name: SpacyEntityExtractor
  dimensions:
  - PERSON
- name: EntitySynonymMapper
policies:
- name: AugmentedMemoizationPolicy
- name: TEDPolicy
  epochs: 40
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
