version: '3.4'
services:
  hear-me-rasa-x:
    build:
      context: .
      dockerfile: ./compose/rasa-x/Dockerfile
    image: hear-me-rasa-x
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    environment:
      RASA_X_PASSWORD: Kamil100!
    command: |
      x --no-prompt --enable-api --port 5005 --cors "*"
#    command: ["x", "--enable-api", "--port", "5005", "–-cors", "*", "–-no-prompt"]
#      - train
#      - x --no-prompt
#      - x
#    command: [ "bash", "run.sh" ]
#    command: [ "bash", "x"]
#    command:
#      - x
  hear-me-rasa-action:
    build:
      context: .
      dockerfile: ./compose/action/Dockerfile
    # tag it with the registry of the microk8s cluster
#    image: localhost:32000/hear-me-rasa-action:0.0.1
    image: hear-me-rasa-action
#    command: [ "bash", "run.sh" ]
#    command:
#      - run actions
    expose:
      - "5055"
    ports:
      - 5055:5055

