FROM rasa/rasa:main-full

#COPY actions /app/actions

USER root
#RUN pip3 install rasa-x --extra-index-url https://pypi.rasa.com/simple
RUN pip install --no-cache-dir -r /app/actions/requirements-actions.txt
RUN pip install rasa-x --extra-index-url https://pypi.rasa.com/simple
RUN python -m spacy download pl_core_news_sm
#RUN pip install -U pip setuptools wheel \
#    && pip install -U spacy \
##    && python -m spacy download pl_core_news_lg
#    && python -m spacy download pl_core_news_sm


USER 1001
#CMD ["run"]
CMD ["x"]

